yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField()
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-created']


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='user_author'
            ),
            models.CheckConstraint(
                name='prevent_self_follow',
                check=~models.Q(user=models.F("author"))
            ),
        ]

yatube/posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Comment, Post

User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }
        help_texts = {
            'text': 'Оставьте комеентарий',
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def pages(request, posts, amount):
    paginator = Paginator(posts, amount)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()
    page_obj = pages(request, posts, settings.POSTS_AMOUNT)

    context = {
        'main': True,
        'page_obj': page_obj
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = pages(request, posts, settings.POSTS_AMOUNT)

    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()

    if request.user.is_authenticated:
        following = Follow.objects.filter(user=request.user,
                                          author=author).exists()
    else:
        following = False

    page_obj = pages(request, posts, settings.POSTS_AMOUNT)

    context = {
        'following': following,
        'author': author,
        'page_obj': page_obj
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.all()

    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


@login_required
def post_create(request):
    # C какой формой будет работать этот view-класс
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )

    if form.is_valid():
        form.instance.author = request.user
        form.save()
        return redirect('posts:profile', username=request.user.username)
    template = 'posts/create_post.html'
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    template = 'posts/create_post.html'
    form = PostForm(instance=post)
    if request.user != post.author:
        return redirect('posts:post_detail', post.pk)
    if request.method == 'POST':
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post
        )
        if form.is_valid():
            form.save()
        return redirect('posts:post_detail', post.pk)
    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/index.html'
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = pages(request, posts, settings.POSTS_AMOUNT)

    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follows = request.user.follower.all()
    follows.filter(author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{%extends 'base.html'%}
{% load user_filters%}

{% block title %}
  {% if form.instance.id is None %} 
    Новый пост
  {% else %} 
    Редактировать пост
  {% endif %} 
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if form.instance.id is None %} 
              Новый пост
            {% else %} 
              Редактировать пост
            {% endif %}          
          </div>
          <div class="card-body">        
            <form method="post" enctype="multipart/form-data" action="
              {% if form.instance.id is None %} 
                {% url 'posts:post_create' %}
              {% else %}
                {% url 'posts:post_edit' form.instance.id %}
              {% endif %}"
            > 
              {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                  {% if field.help_text %}
                    <small 
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted"
                    >
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                {% if form.instance.id is None %}
                  Добавить
                {% else %}
                  Сохранить
                {% endif %}               
                </button> 
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/posts/group_list.html
{%extends 'base.html'%}

{% block title %}
    Записи группы «{{ group.title }}»
{%endblock%}

{% block content %}
  <div class="container py-5">
    <h1> {{ group.title }} </h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in page_obj %}
      {% include 'includes/post.html' %}
      <hr>
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>  
{% endblock %}   

yatube/templates/posts/index.html
{% extends 'base.html' %} 
{% load cache %} 

{% block title %}
  {% if main is True %}
    Последние обновления на сайте
  {% else %} 
    Моя лента
  {% endif %} 
{% endblock %}

{% block content %}
  <div class="container py-5">
    {% include 'includes/switcher.html' %}
    {% cache 20 index_page page_obj %}
      {% for post in page_obj %}
        {% include 'includes/post.html' %}
        <hr>
      {% endfor %}
    {% endcache %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}   

yatube/templates/posts/post_detail.html
{%extends 'base.html'%}
{% load thumbnail %}
{% load user_filters %}

{% block title %}
   {{ post.text |truncatechars:30 }}...
 {%endblock%}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}   
            <li class="list-group-item">
              Группа:
              <a href={% url 'posts:group_list' post.group.slug %}>{{ post.group.title }}</a>
            </li>
          {% endif %} 
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  {{ post.author.posts.count }}
          </li>
          <li class="list-group-item">
            <a href={% url 'posts:profile' post.author %}>
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <p>
          {{ post.text|linebreaks }}
        </p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {% if request.user == post.author%}
          <a class="btn btn-primary" href= {% url 'posts:post_edit' post.id %}>
            Редактировать запись
          </a>
        {% endif %}
        <h2>Комментарии</h2>
        <hr>
        {% include 'includes/comments.html' %}
      </article>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{%extends 'base.html'%}

{% block title %}
  {{ author.get_full_name }} профайл пользователя
{%endblock%}

{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ page_obj.paginator.count }} </h3>
    <div class="mb-3">
      {% if request.user != author %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}
      {% endif %}
    </div>   
    {% for post in page_obj %}  
      {% include 'includes/post.html' %}
      <hr>
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}   